//
// Created by gwendal on 1/27/19.
//

#ifndef GWENMISSIONSUBMIT_CONSTANTS_H
#define GWENMISSIONSUBMIT_CONSTANTS_H
enum { INVALID_SOCKET = -1, SOCKET_ERROR=-1, DEFAULT_PORT=8080, WAIT_LEN = 100};
#endif //GWENMISSIONSUBMIT_CONSTANTS_H
